### ISSUE TITLE
bug in log level

### ISSUE THREAD

**Issue by amcadmus** [deepmodeling/deepmd-kit#381]
I want to discuss the determination of the `log_level` by `argparse`, the code is in the following
https://github.com/deepmodeling/deepmd-kit/blob/18ba5b19d8d2d237e600c6478ba8c8ba59e48d7b/source/train/main.py#L42-L50

Surprisingly, the action of `"count"` is to ADD the number of flags to the default value of `log_level`. Then if one sets `-vvv`, he/she will have a `log_level` of `5` rather than `3`. To reproduce this behavoior, 
```
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("-v", default=2, action="count", dest="level")
args = parser.parse_args(['-vvv'])
print(args.level)
```

**Comment by amcadmus** [comment]
@marian-code  Please take a look.

**Comment by marian-code** [comment]
OK, that behaviour is a really unexpected and unintuitive, I will take a look at it.

**Comment by marian-code** [comment]
I have realized the current solution is a complete mess. For instance there is no way of setting log level to 0 because if you do not pass any `-v` arguments it just defaults to 2.

I see here few possible reasonalbe solutions.

1. keep the curent system but set `default=0` and nothing has to be changed. But downside is that by default user would not see any output unless he passes at least one `-v` argument. You would need to pass `-vv` to see logs that are now considered "default" - the INFO level. This is unfortuantelly not really intuitive.
2. The other option is to use someting of this style: 
    ```python
    parser.add_argument("-l", "--log-level", choices=['DEBUG', 'INFO', 'WARNING', 'ERROR'], default="INFO")
    ```
   Which is quite clear and consise but lacks the familiarity of `-v` style setting as is custom for linux tools.
3. The third solution is a bit hack-y but preserves the current behaviour with one minor change (the `-v` count is shifted so you 
    need one more `v` for the same level as before):
    ```python
    parser.add_argument("-v", default=1, action="count", dest="level", help="1(-v)=ERROR, 2(-vv)=WARNING, 3(-vvv)=INFO " 
                        "and 4(-vvvv)=DEBUG.  Default is INFO")
    args = parser.parse_args()
    # levels: 2=ERROR, 3=WARNING, 4=INFO, 5=DEBUG
    # adjust if `-v` was not passed in
    if args.level == 1:
        args.level = 4

   args.level -= 2  # this gives results excatly as they are expected in current state i.e. levels from 0 to 3
   ```

Please let me now what you think is the best solution.

**Comment by amcadmus** [comment]
1 is very good but we may want a default behavior of `log_level == 2`
I do not like the logic used by solution 3
Thus I prefer the second way, it may be improved as 
```python
parser.add_argument("-l", "--log-level", choices=['DEBUG', 3, 'INFO', 2, 'WARNING', 1, 'ERROR', 0], default="INFO")
```
so one can quickly set the log level to for example `ERROR` by 
```
dp train -l 0 input.json
```
