### ISSUE TITLE
v2.0.0-beta.0: Nan in summary histogram #689

### ISSUE THREAD

**Issue by amcadmus** [deepmodeling/deepmd-kit#692]
Hello,
I try to run v2.0.0-beta.0 with:
  "loss": {
        "start_pref_e": 0.02,
        "limit_pref_e": 1,
        "start_pref_f": 1000,
        "limit_pref_f": 1,
        "start_pref_v": 0.02,
        "limit_pref_v": 1".
And an error appears:
        " tensorflow.python.framework.errors_impl.InvalidArgumentError: Nan in summary histogram for: filter_type_all/bias_2_0_0_1/histogram "

But when I set {"start_pref_v": 0, "limit_pref_v":0}, it works. I was wondering why I can not train with virial, could you please help me what I should do?
Thanks,

( Also, it works with v1.3.3 )

_Originally posted by @AlexanderOnly in https://github.com/deepmodeling/deepmd-kit/discussions/689_

**Comment by amcadmus** [comment]
@marian-code Could you please take a look at the issue?

**Comment by marian-code** [comment]
This should be a consequence of numerical instability that can be encountered in the first iterations mostly due to wrong choice of training parameters.

See: [SO-1](https://stackoverflow.com/questions/39854390/nan-in-summary-histogram) and [SO-2](https://stackoverflow.com/questions/61338394/why-does-tensorboard-give-this-error-invalidargumenterror-nan-in-summary-histo)

Change of training parameters should be able to remedy this in most cases. I suggest that this will not be labeled as bug.

We have two options here:

  1. Leave it as is and update the docs with info that if you are encountering this error your train parameters are most likely set wrong.
  2. Catch the exception and do not log data from that iteration but display a clear warning that you are probably doing something wrong and your training will most likely not converge.

Please let me know which one do you prefer.

**Comment by amcadmus** [comment]
> This should be a consequence of numerical instability that can be encountered in the first iterations mostly due to wrong choice of training parameters.
> 
> See: [SO-1](https://stackoverflow.com/questions/39854390/nan-in-summary-histogram) and [SO-2](https://stackoverflow.com/questions/61338394/why-does-tensorboard-give-this-error-invalidargumenterror-nan-in-summary-histo)
> 
> Change of training parameters should be able to remedy this in most cases. I suggest that this will not be labeled as bug.
> 
> We have two options here:
> 
> 1. Leave it as is and update the docs with info that if you are encountering this error your train parameters are most likely set wrong.
> 2. Catch the exception and do not log data from that iteration but display a clear warning that you are probably doing something wrong and your training will most likely not converge.
> 
> Please let me know which one do you prefer.

Thanks for the reply! I realize that it should be attributed to the bug fixed in #685 . Let's see if  @AlexanderOnly still encounters the bug after upgrading to v2.0.0-beta2
