### ISSUE TITLE
How does deepmd use MPI?

### ISSUE THREAD

**Issue by zhixia721** [deepmodeling/deepmd-kit#9]
I tried:
mpirun -np 4 do_train water.json
However, it looks the code does not run correctly. I got repeated run information. Do you have any suggestions about how to use mpirun? 
And how about the scaling? Do you have any benchmark?

Thank you!

**Comment by amcadmus** [comment]
For MD simulation: the MPI parallelization is supported. Simply compile lammps with the MPI support (typically compile with "make mpi"), then you can run MPI parallelized deepmd simulations. More details can be found in 
installation: https://github.com/deepmodeling/deepmd-kit#install-lammpss-deepmd-kit-module
usage: https://github.com/deepmodeling/deepmd-kit#run-md-with-lammps.

For training: The current version of deepmd-kit only supports multi-threading parallelization, this should be enough for training with deepmd-kit on one node of a cluster. The distributed parallelization will come with the next release.  The training accelerated by GPU is highly recommended.

**Comment by fppsvz** [comment]
Hello to everybody!
I will follow this issue to kindly ask a clarification on how practically parallelisation works within deepMD training, to the experts. What is not exactly clear to me is where parallelisation enters in the game. If I have, say, 2500 training batches containing 2 structures each, would it run ideally on 2 structures in parallel right? I'm asking this because with these very same condition using 2 OpenMP threads; if I increase the batch size to 4 structures and I use 4 OpenMP threads it doesn't seem to show any scaling (takes like double the time whereas I was expecting it to take about the same time). Thanks for your time.
All the best.
